### ISSUE TITLE
POV: Next episodes disappear after watching a show.

### ISSUE THREAD

**Issue by Getterbetter** [kodifitzwell/repo#1]
Firstly a huge thank you and shout out to kodifitzwell for POV - it’s awesome and hands down my favorite Kodi add on.

I’ve been experience a strange behavior when launching content from the ‘next episodes’ section.

In short, if I open the next episodes menu, all my shows load normally. I select a show, pick and stream and it loads fine. However, when I exit the stream, most and sometimes all the episodes from the next episodes section disappear. It’s as if it’s trying to reload them but fails. If I go back to TV shows and re-enter Next Episodes then all my shows are there. I’ve include two photos, one from before & after launching a stream. The problem this creates is it breaks my widgets, so all my next episodes disappear after watching something.

I’d originally noticed the issue when launching from widgets, so I spent ages trying to troubleshoot the skin settings. But this is from a clean install of Kodi v20.5 with just POV v4.07.14 installed on an ATV4 tvOS 17.5. I thought it was an issue with Trakt but the same behavior doesn’t occur when watching something from the ‘In Progress Epsiodes’ section 
![IMG_5240](https://github.com/user-attachments/assets/e0bd098c-233b-4208-b7d1-e8d664267acf)
![IMG_5241](https://github.com/user-attachments/assets/778a1323-eadc-452b-acbf-6cf60e0fef43)

Issue occurs on both Kodi v20.5 & v21.0

Logs at the time of the behavior: https://paste.kodi.tv/netetanuci. 

Huge thanks again for putting together this app and appreciate any help.

**Comment by kodifitzwell** [comment]
thanks for using the addon and the detailed report.

a few questions so I can try to duplicate.  are you manually stopping the episode?  is atv your only device or does this happen on other devices?

**Comment by Getterbetter** [comment]
Thanks for your help and coming back to me so quickly.

Yes, I’m manually stopping the video. The behaviour occurs regardless of when I stop the issue, but I can consistently reproduce it after watching something for 5-10 seconds.

Yes, I’m only running it on an ATV but I can load it onto my Mac and let you know.

**Comment by Getterbetter** [comment]
Can confirm it’s not happening on MacOS with Kodi v21.0

**Comment by kodifitzwell** [comment]
>Can confirm it’s not happening on MacOS with Kodi v21.0

not happening as in the list is populated correctly?  that's good news.

bad news is I don't have the ability to test on anything apple.  but there is no os specific code in the addon, so I'm inclined to believe there are some device specific resource limitations.

on the atv, do you paginate lists?  what happens if you paginate lists at 100 and select a popular trakt list like "latest tv shows?"  do you get 100 items?

https://github.com/user-attachments/assets/8523fa78-e64a-4c01-8176-c923fe9202d8

**Comment by Getterbetter** [comment]
Yes, the list is populating correctly. From what I can tell when it happens on the ATV, it’s only from the Next Episodes. Even the In Progress Episodes section works fine.

Thanks for the video, that’s very kind. Those settings were already applied (I believe they are the default) and was able to find several lists with 100+ items. They all loaded fine. 

I don’t blame you for being at a loss here, particularly since it’s only affecting ATV. I’ve asked my brother to test too to see if it’s just my device.

**Comment by Getterbetter** [comment]
One question, is there anything unique that happens after watching something from Next Episodes that doesn’t exist elsewhere?

**Comment by kodifitzwell** [comment]
>Even the In Progress Episodes section works fine.

well generally this section probably has fewer items?  which is why I asked about the trakt lists.  I thought it might be a number of threads issue given the "info" message "waiting on thread..."

>One question, is there anything unique that happens after watching something from Next Episodes that doesn’t exist elsewhere?

I don't believe so.  Next Ep/In Progress use the same function and clearly there are no issues with either before the play.

is your output to bluetooth?  what happens if you just use the built-in speakers?

**Comment by Getterbetter** [comment]
`well generally this section probably has fewer items? which is why I asked about the trakt lists. I thought it might be a number of threads issue given the "info" message "waiting on thread..."`
Ok, I can see your thinking. 

`is your output to bluetooth? what happens if you just use the built-in speakers?`
Yeh, I had my AirPods in. I tried again without Bluetooth (i.e. built in speakers) and the issue reoccurred where the Next Episodes list of shows was not showing all TV shows. Logs: https://paste.kodi.tv/vekawisoni

**Comment by umbrellaplug** [comment]
I've run into issues with the scrapers causing threading issues on the atv devices. The max thread was 88. If you could somehow limit your threads to a max at a time you might be able to help this issue. It might take a little longer to load the list though.
