### ISSUE TITLE
Trakt doesn't work with pov

### ISSUE THREAD

**Issue by Mollver** [kodifitzwell/repo#1]
Hi,
Recently, Trakt connection with pov stoped, and when I tried to reauthorize it, it gave me error.

As I know trakt got down days ago so maybe it's related.

**Comment by kodifitzwell** [comment]
try to authorize and if it fails, show me a `kodi.log` file.

to test, I authorized a clean install just now with no issues.

**Comment by Mollver** [comment]
https://paste.kodi.tv/wevaxihola
I think this link should give you my log

**Comment by kodifitzwell** [comment]
how free disk space do have on your device?  rw file permissions?

in the log file this is the error:

    Error Type: <class 'sqlite3.OperationalError'>
    Error Contents: disk I/O error

you can try this:

1. from kodi settings/my addons, disable the addon

2. from kodi file manager, browse to profile directory/addon_data/plugin.video.pov and delete the file(s) `traktcache<number>.db`

3. from kodi settings/my addons, enable the addon

4. from the addon settings/clean settings files and clear caches, clear all caches

**Comment by Mollver** [comment]
I don't think there is a lot free space as I'm using Google tv device.

I'm going to try that

**Comment by Mollver** [comment]
As always you are a savior 🙏 
It's works again, Thank you and I appreciate your work 🙌
