### ISSUE TITLE
Watchlist 

### ISSUE THREAD

**Issue by djdirty60** [kodifitzwell/repo#1]
Good day,

Is it possible that the watchlist is ascending rather than descending? So from oldest release to latest release date.

Thank you in advance

**Comment by kodifitzwell** [comment]
not a hard "No", but I really dislike having to create another asc/desc setting for every sort setting.

on the standard skin (I use Estuary), at the top of a list hitting "up" cycles down to the last item on the list.  thus being able to browse asc.  does the skin you use not allow this?
