### ISSUE TITLE
Pov doesn't ask to resume watching

### ISSUE THREAD

**Issue by Mollver** [kodifitzwell/repo#1]
Hi, I'm using Kodi with google chromcast,
When I want to continue watching Movie or episode it's not asking if i want to resume from where I stop or not, this issue since last a few updates.
Wish you help

**Comment by kodifitzwell** [comment]
thank you for reporting the issue.  it is fixed in my tests with version `4.07.05`.  please test and lmk if the issue is not resolved or close the issue if completed.

**Comment by Mollver** [comment]
> thank you for reporting the issue. it is fixed in my tests with version `4.07.05`. please test and lmk if the issue is not resolved or close the issue if completed.

Yeah Ithink it's works again, thanks you for hard work.
