### ISSUE TITLE
Trakt calendar

### ISSUE THREAD

**Issue by Arthur1967** [kodifitzwell/repo#1]
How do I get my Calendar to start on today and show days previous thank you

**Comment by kodifitzwell** [comment]
there are calendar settings in the trakt section as you can see in the attachment.

I don't remember changing much of the trakt related code and don't use trakt to capture my watched.  so if the settings are not working as expected, please give me a visual of what you are seeing so I can reproduce and attempt to fix.

![clipboard](https://github.com/kodifitzwell/repo/assets/105136042/38427ab6-dbd0-43d9-9cc2-190c8f694eeb)

**Comment by Arthur1967** [comment]
Sorry I must've missed that. Have a good day. You can post this now or I will.
