### ISSUE TITLE
Onemoar playback error

### ISSUE THREAD

**Issue by epidoma** [kodifitzwell/repo#10]
hey.
I have seen from another issue posted here that you use libreelec.
There has been a bug in onemoar when using coreelec ,and i guess it should also appear in libreelec then?
so anyways if you would please like to test this scenario.
you must have arctic horizon 2 skin (default views) or arctic fuse(default views) installed.
To replicate this bug go to onemoar addon then to tv shows,trending and look for friends tv show ( or actualy just search for it),go to season 4 episode 1
it must look like in this picture or very similar if you use arctic fuse
https://postimg.cc/47c8zFTN
and then start first or seccond link (cocoscraper default settings)

first link name
Friends:.The.Complete.Series.[Seasons.1-10].(20.Blu-Ray.1080p)
second link name
Friends-S04-BDRemux-1080p

and nothing will happen...no error popup nothing. its like i never pressed a link..
both links from this example work fine on all your other addons under same circumstances

this was just one example , i found out that maybe around 30% of all links for diferent tv shows are not working in onemoar when using this 2 very popular skins.

kodi log shows
error <general>: EXCEPTION: Kodi is not playing any media file
and onemoar log
[ plugin.video.onemoar: ERROR ]: From func name: /resources/lib/menus/tvshows.py.tvshowDirectory() Line # :1716
                       msg : TypeError -> quote_from_bytes() expected bytes

I hope you can replicate this on your end .

**Comment by kodifitzwell** [comment]
for the first item, look at the magnetdl [file listing](https://www.magnetdl.com/file/1865841/friends-the-complete-series-seasons-1-10-20-blu-ray-1080p/).  how can any addon determine what is the correct file to play?  some remuxes are like this.

>I hope you can replicate this on your end .

try the default skin and let me know what happens.

with the default skin:

    Friends:.The.Complete.Series.[Seasons.1-10].(20.Blu-Ray.1080p)

does not play and the addon automatically plays

    Friends-S04-BDRemux-1080p

successfully (be sure in settings "Source Options" "Only try one source" is disabled).  when you browse the pack, it is a series of mkv files appropriately named per episode.

**Comment by epidoma** [comment]
you are right about first link. i am sorry it will not play in any addons.
seccond link Only try one source is disabled.
i did a clean install for this so all default settings are set.
and seccond file does not play when using arctic skins.(in default skin it plays fine)
it plays fine in arctic skins if i disable default views and turn off directories under (like i showed in screenshoot)
so maybe this error is with that  /resources/lib/menus/tvshows.py.tvshowDirectory() Line # :1716
i am surprised it works for you .

**Comment by epidoma** [comment]
I will close this since you can't replicate.
thanks for taking time to test.

**Comment by kodifitzwell** [comment]
>i am surprised it works for you .

well as I said, I only tried the default skin.

>and seccond file does not play when using arctic skins.(in default skin it plays fine)
it plays fine in arctic skins if i disable default views and turn off directories under (like i showed in screenshoot)

I am suprised it doesn't work, the code when you select an item, then scrapes, then you select a source, then the next source is auto selected on fail, etc... really has little to do with skins.  it is my opinion that skins should follow the default skin behavior.  if you turn off skin settings and it works then it should be addressed with the skin dev.  addon devs should not have to code for specific skins, even moreso for specific settings within a skin.

**Comment by epidoma** [comment]
> > i am surprised it works for you .
> 
> well as I said, I only tried the default skin.
> 
> > and seccond file does not play when using arctic skins.(in default skin it plays fine)
> > it plays fine in arctic skins if i disable default views and turn off directories under (like i showed in screenshoot)
> 
> I am suprised it doesn't work, the code when you select an item, then scrapes, then you select a source, then the next source is auto selected on fail, etc... really has little to do with skins. it is my opinion that skins should follow the default skin behavior. if you turn off skin settings and it works then it should be addressed with the skin dev. addon devs should not have to code for specific skins, even moreso for specific settings within a skin.

I tough you did tried with arctic skins. i missread.
i would agree with you that skin dev should handle this. but the thing is it works with other addons, and if i modify player.py  then it works with onemoar aswell...but i lose autoplay.
And umbrella added alot of code changes for arctic skins starting from version v6.6.28. actually everything works fine with v6.6.27, after that it gets broken on coreelec
so i do think that maybe video addon is at fault here.
[player.zip](https://github.com/kodifitzwell/repo/files/15400451/player.zip)

**Comment by kodifitzwell** [comment]
have you tried enabling debug and setting the level to debug(extra info) in the addon settings?

if the arctic widgets weren't such a pain to set up in I might have taken a shot at it.

**Comment by epidoma** [comment]
@kodifitzwell 
thats ok mate. I didnt want to bother you,and anyways with my modified player.py everything other then autoplay works as it should.
It's just when i have seen in your post that you are on libreelec i tought finally maybe this gets fixed,because you can recreate it ( on windows and android it works fine)
As for debug log,sure it shows errors when resolving ccurl file.
and yes ipv6 is disabled and dns is 1.1.1.1 or 8.8.8.8 and also tried default from my ISP and if i curl file from ssh it works fine.
its something else and im not a coder and it's beyond me to fix it. best i could do was to traceback to last working version of umbrella look at commits and figuring out that player.py lost this entery self.playeronly = getSetting('use.playeronly') == 'true'
i edited the file put those enterys back and it worked 
oh and onemoar log shows everythig is fine.

thanks for your time man, dont bother with it i will just use my player.py 
Oh and please keep the forks running you are doing a great job,i'm a big big fan .
