### ISSUE TITLE
POV feature request - Simkl

### ISSUE THREAD

**Issue by Xyl-AU** [kodifitzwell/repo#11]
This is probably a large undertaking to implement so fair enough if not, but having Simkl as an alternative to Trakt for managing lists would be great as Simkl has much better support for anime. The only plugin that I'm aware of that has some sort of Simkl implementation is [Otaku](https://github.com/Goldenfreddy0703/Otaku), but that is limited to anime when I would like to use it for everything.

**Comment by kodifitzwell** [comment]
>The only plugin that I'm aware of that has some sort of Simkl implementation is Otaku

OneMoar has simkl, though it is untested by me. :)

>Simkl has much better support for anime

so from my understanding anime is more than just the meta/tracking from simkl.  where those addons excel is in the unique file naming coventions used by anime.

POV/Dradis filters are geared towards Sxx/Exx for shows and thats where it is less effective with anime.

**Comment by kodifitzwell** [comment]
sounds like you have done the scraper work.

so just thinking out loud here as it seems like an interesting project...

adding simkl for anime would mean pulling the meta there rather than tmdb.  its been a while, but last I looked simkl provided a sizeable amount of meta and poster/fanart (something that trakt does not).  so techincaly could just remove tmdb all together since we're now using simkl for meta and tracking.  guess we don't need trakt for tracking either now, remove that.

so isn't that what Otaku is now?  does it not offer non-anime content through simkl?  or is it the UI/customization/speed you are looking for from POV for anime/non-anime?

**Comment by TwilightMercy** [comment]
> Sort of. FWIW I've been able to get Fen Light + CocoScrapers to work with anime perfectly fine with just a couple of tweaks. Namely, changing the Torrentio URL to include Nyaa and not exclude non-English results, bypassing the name check for Nyaa results from Torrentio as it's already mapped almost perfectly, and adding the following regex to the list in `seas_ep_filter`, which can find episodes with only an episode name and not a season name but will not return upon matching numbers if there is a traditional season or episode marker also in the filename.
> 
> 
> 
> `r'(^(?=.*[.-]e?0*<<E>>[.-])(?:(?!((?:s|season)[.-]?\d+[.-x]?(?:ep?|episode)[.-]?\d+)|\d+x\d+).)*$)'`
> 


Hi @Xyl-AU,

Are the changes you've made to CocoScrapers to improve anime scraping through Torrentio (and NYAA) - are only in torrentio.py file? Or also in another files?

If possible, I would love to try your modified version to get more anime results through CocoScrapers :)
If possible, can you share your modified torrentio.py file/s?

🙏🏻

**Comment by kodifitzwell** [comment]
I decided I won't implement this.

I wrote a simple module to poll the meta from simkl and build some lists in POV.

for non anime the simkl meta is not the same relative what tmdb can provide so I'm not willing to switch all out.

currently the non personal lists generated are from trakt or tmdb (1 api call).  then the addon takes the ids (tmdb or imdb) from that and looks it up at tmdb (2 api call) and builds the lists from the meta.  this is really the point where you want the simkl api for anime seasons/episodes.

trakt will provide a tmdb/imdb in the first call but tmdb can not be forced to provide the imdb (or artwork) needed to look up meta at simkl without a third api call.  then there would be a fourth call to simkl to get the meta and build the list.

so why not cut out tmdb and just get non personal lists from trakt and simkl.  trakt does not provide art and the non anime art from simkl didn't seem great.  also, the trending/popular/genre/etc lists from simkl didn't seem as "current" as tmdbs.  maybe due to less users?

simkl might excel at meta for anime but (for me) its not enough of a reason to compromise on the non anime.

**Comment by TwilightMercy** [comment]
> 
> @TwilightMercy Here - just rename this back to torrentio.py and replace it in CocoScrapers. https://files.catbox.moe/ctustp.py
> 
> The regex I mentioned applies to the video plugin (POV/Fen/Umbrella) and probably isn't necessary in most cases - I've only needed it a couple of times. Depending on what you use you'll have to add it yourself, but basically find the seas_ep_filter function in probably source_utils.py and add
> 
> `string7 = r'(^(?=.*[.-]e?0*<<E>>[.-])(?:(?!((?:s|season)[.-]?\d+[.-x]?(?:ep?|episode)[.-]?\d+)|\d+x\d+).)*$)'` under the other regexes and `string_list_append(string7.replace('<<E>>', episode_fill))` at the end of all the other string_list_append calls.

Thank you very much!
I've saved the file you sent as torrentio.py in CocoScrapers.

I am using Fen. so in addition to torrentio.py, you've modified source_utils.py in Fen as well?
Just so I don't miss any change, will you able to send me your modified source_utils.py of Fen's last version?
That way I'll have the accurate code : )

Thank you very much!

**Comment by TwilightMercy** [comment]
> 
> Here's the modified source_utils: https://files.catbox.moe/13l8i6.py
> 
> The additions are line 151 and line 166.
> 
> I say it's mostly unnecessary because it only really applies where there's only a contextless episode number to match. And it's a bit of a pain to modify each update - though I suppose since Fen is discontinued it doesn't matter. There's also a slim chance that it could match the wrong file since the Regex works by excluding files that have a traditional episode marker in them. I haven't come across this issue but if you run into this problem it may be why.
> 
> An example of a show to test with is Chi's Sweet Home season 1. Without the Torrentio mod, you get zero results. With the Torrentio mod, you get 2 results (but the first one is actually a mismatch because there's a remake with the same name). The second result is the correct one, but without the source_utils mod it will not match a file and will fail.

Thank you, I tested with and without the source_utils.py mod, and also with and without Torrentio mod and it works great. So much more results for Anime shows.

I have 2 questions:

1. CocoScrapers is also scraping in ElfHosted (Torrentio fork - https://torrentio.elfhosted.com/) in elfhosted.py file. The code is already the same except in elfhosted.py it is already looking for all providers so no need to change URL to include Nyaa:
```
self.movieSearch_link = '/stream/movie/%s.json'
self.tvSearch_link = '/stream/series/%s:%s:%s.json'
```
I tried to do same mods from torrentio.py to elfhosted.py but no changes in results. I tested also the addons in Stremio and barely anime results from ElfHosted, so I guess it's backend is different and no NyaaSi provider exists.


2. CocoScrapers has already NYAA Provider in nyaa.py file, but barely provides results for Animes. Are you familiar with it's code? maybe something can also be improved for matching?

Thanks again

**Comment by TwilightMercy** [comment]
> > > Here's the modified source_utils: https://files.catbox.moe/13l8i6.py
> > > The additions are line 151 and line 166.
> > > I say it's mostly unnecessary because it only really applies where there's only a contextless episode number to match. And it's a bit of a pain to modify each update - though I suppose since Fen is discontinued it doesn't matter. There's also a slim chance that it could match the wrong file since the Regex works by excluding files that have a traditional episode marker in them. I haven't come across this issue but if you run into this problem it may be why.
> > > An example of a show to test with is Chi's Sweet Home season 1. Without the Torrentio mod, you get zero results. With the Torrentio mod, you get 2 results (but the first one is actually a mismatch because there's a remake with the same name). The second result is the correct one, but without the source_utils mod it will not match a file and will fail.
> > 
> > 
> > Thank you, I tested with and without the source_utils.py mod, and also with and without Torrentio mod and it works great. So much more results for Anime shows.
> > I have 2 questions:
> > 
> > 1. CocoScrapers is also scraping in ElfHosted (Torrentio fork - https://torrentio.elfhosted.com/) in `elfhosted.py` file. The code is already the same except in `elfhosted.py` it is already looking for all providers so no need to change URL to include Nyaa:
> > 
> > ```
> > self.movieSearch_link = '/stream/movie/%s.json'
> > self.tvSearch_link = '/stream/series/%s:%s:%s.json'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried to do same mods from `torrentio.py` to `elfhosted.py` but no changes in results. I tested also the addons in Stremio and barely anime results from ElfHosted, so I guess it's backend is different and no NyaaSi provider exists.
> > 
> > 2. CocoScrapers has already NYAA Provider in `nyaa.py` file, but barely provides results for Animes. Are you familiar with it's code? maybe something can also be improved for matching?
> > 
> > Thanks again!
> 
> Re: elfhosted - going to the result JSON files confirms that yeah it's just not picking up the same results. Why that is, I have no idea.
> 
> As for the CocoScrapers Nyaa scraper, it first uses the Nyaa search. This is different than Torrentio, which, rather than trying to match a name to a torrent through search, looks at all the torrents on Nyaa and tries to match them to a name.
> 
> Back to the Chi's Sweet Home example - it will search "chis sweet home". Nyaa is sensitive to that apostrophe that's missing, and so won't return results. Once it's scraped the results from the page, it will do a lot of checking against the titles and season/episode indicators to try to ensure it's not a mismatch. I find this process gets rid of most anime results, probably because of alternate titles and less standardised episode labelling. I thought about trying to improve it, but I honestly just can't be bothered when just modifying the Torrentio file does most of the work.
> 
> There are only a few cases where Torrentio hasn't been good enough, namely AoT final chapters because of its weird release across databases, and once I was looking for the Netflix dub of Vinland Saga season 2 but it only found a release with the Sentai one because I'm guessing it flagged it as a duplicate.

I see.
By the way, do you know if any torrentio mod to CoCoScrapers can be done to improve WWE Shows? (similar issue - Stremio with Torrentio finds, in Fen/CoCo not)
