### ISSUE TITLE
[Infinity] Widget context menu not honoring settings in Arctic Fuse

### ISSUE THREAD

**Issue by Liquidrag** [kodifitzwell/repo#13]
First off, thank you for this fork, I'm really enjoying it! 

I'm not sure if it is just in arctic fuse, but I have these items turned off in settings, but they still show up in the context menu.  I only have trakt manager, clear providers, rescrape, autoplay, select source, find similar, browse series, and browse episodes enabled.

<img width="1279" alt="Screen Shot 2024-08-29 at 4 20 53 PM" src="https://github.com/user-attachments/assets/f7a1a96a-f337-4f90-9ab1-30272cb0f298">

**Comment by kodifitzwell** [comment]
I don't believe this is something I altered from the original addon.  if that is true, surprising no one has ever reported it.

the context menu needs a refactor, but I believe I have fixed it for now in `4.09.01`.  please keep in mind that even though enabled, some items require multiple conditions to be true to show in the context.  please close the issue if it satisfies the request or lmk if there are still issues.

**Comment by Liquidrag** [comment]
Thank you!
