### ISSUE TITLE
[Request] To create an option to make hidden any scraping and resolving.

### ISSUE THREAD

**Issue by derrgoo** [kodifitzwell/repo#14]
I feel POV is so fast I don't need any dialog to show if played auto play. Press play and does all in background and poof movie playing. Love your work 👍

**Comment by kodifitzwell** [comment]
thanks for kind words.

it's fast now that all the source websites are working, but bitsearch in particular seems to go down for me every 10 days or so.  at that point the builtin 7sec timeout kicks in and that's kind of a longish time with no indication to the user of whats going on.  I will keep it in mind but will probably never completely remove it, if anything I might offer the option of a background process dialog similar to the Playback Loading Progress setting.

**Comment by kodifitzwell** [comment]
>You might check out umbrella.

you might check out Infinity.  alot of the work I did in Infinity went to that addon, but started in Dradis.

>Background process dialog similar to the Playback Loading Progress setting.

anyway, I have it roughly worked out for POV.  what should go in the top corner?  the quality totals like Dradis, the # totals of remaining providers, or something else?  the text is truncated if too long.

![progressbg](https://github.com/user-attachments/assets/0920a598-ab06-4646-aebd-4d3a967e8563)

**Comment by derrgoo** [comment]
I think that idea is great. Keeps very minimal. Thanks

**Comment by derrgoo** [comment]
"you might check out Infinity. alot of the work I did in Infinity went to that addon, but started in Dradis."

Yes! Looks like Background works great as you showed in the picture. So fast!

**Comment by kodifitzwell** [comment]
try `4.09.17` and close the issue if resolved, else lmk if there is an issue.

https://github.com/user-attachments/assets/5b39040b-1d1a-4cc8-9f45-a1c9beca31b1

**Comment by derrgoo** [comment]
👍 perfect thank you
