### ISSUE TITLE
Infinity Context menu options in widgets

### ISSUE THREAD

**Issue by Liquidrag** [kodifitzwell/repo#15]
Sorry to bother you again but similar to my previous [issue](https://github.com/kodifitzwell/repo/issues/13#issue-2495627910) Source select has been removed in infinity settings but still shows up, It's also weird because it shows up in umbrella's context menu.

<img width="1436" alt="Screen Shot 2024-09-18 at 10 34 58 AM" src="https://github.com/user-attachments/assets/0748f340-3fea-483e-8e0c-7df6f5bb8361">
<img width="1438" alt="Screen Shot 2024-09-18 at 10 50 16 AM" src="https://github.com/user-attachments/assets/0f5b6212-c703-4938-b054-c2f3eea0750f">

I also have finish watching set as a widget but the "unfinished progress manager - episodes" does not show but does show within the addon. It is the same with umbrella so I will post on his github also. 

From widget
<img width="1435" alt="Screen Shot 2024-09-18 at 11 04 42 AM" src="https://github.com/user-attachments/assets/5792710c-5149-40c7-8491-abf8bc1160c6">
Within addon
<img width="1435" alt="Screen Shot 2024-09-18 at 11 09 51 AM" src="https://github.com/user-attachments/assets/e9aaafff-4acc-4838-9d66-f710aa5b0992">

**Comment by kodifitzwell** [comment]
does the first issue only happen with episodes (not shows or movies)?

what are your settings for:

1. Playback/Enable Playnext Popup
2. Source Options/Movie select action
3. Source Options/TV select action

**Comment by kodifitzwell** [comment]
nvm, I think I fixed the first issue.

for the second issue, Finish Watching is tvshows or individual episodes?

**Comment by kodifitzwell** [comment]
try `4.09.17` and close the issue if resolved, else lmk if either persists.

**Comment by Liquidrag** [comment]
Thank you!
