### ISSUE TITLE
Trakt progress and Scrobble not working

### ISSUE THREAD

**Issue by derrgoo** [kodifitzwell/repo#15]
I have noticed both progress markers missing and no Scrobbling with trakt.

**Comment by kodifitzwell** [comment]
nothing has changed with progress/scrobble in the trakt code for a long time if ever.  do you have a log file so I can see if trakt is returning any response?

**Comment by derrgoo** [comment]
Thanks for your reply. Unfortunately pastbin won't let me upload my log and my MacBook is in repair. As soon as I get it back all find the log. In the meantime I just connected TMDB helper widgets which show progress icons. Pics below. ![image](https://github.com/kodifitzwell/repo/assets/63697905/b24e2209-6289-477d-9007-74453c034688)

This is POV pulling widget

![image](https://github.com/kodifitzwell/repo/assets/63697905/54b3784e-228e-4b4c-9f48-36a9a525c9fb)

**Comment by derrgoo** [comment]
HTTPS://pastebin.com/xAry2DLQ

I think I finally pulled a log. 

I put POV next up as a widget.

**Comment by kodifitzwell** [comment]
>Trakt progress and Scrobble not working

does this refer to inside POV or the addon/skin you have screenshot?

if POV, there is nothing in the log to indicate any issues communicating with trakt.  I'll await your clarification before I start testing because I normally don't use trakt.

if addon/skin ask the dev which list item properties need to be set so I can update.

**Comment by derrgoo** [comment]
Hi. I tested both in POV and Arctic Fuse. Before they always showed up like pulling from POV widgets the same as Fen works. The picture is of the fuse skin pulling next up episodes. The other pic is showing with TMDB pulling but using POV. I think it is changes in omega but not sure if Tikipeter tweaked this to work. However, other skins that worked in nexus don't also work in omega for these playing icons to show up.

**Comment by kodifitzwell** [comment]
>Before they always showed up like pulling from POV widgets... The picture is of the fuse skin pulling next up episodes. The other pic is showing with TMDB pulling but using POV. I think it is changes in omega...

so doesn't really sound like a trakt progress/scrobble issue.  

I think the same dev authors both skin and addon.  sounds like a skin issue.  did you "ask the dev which list item properties need to be set" so I can update?  help me help you.

>not sure if Tikipeter tweaked

I'm sure they did because they are amazballs.

**Comment by derrgoo** [comment]
I put a request in to jurial to show us where to add list items.  All let you know when he answers. He is usually very helpful.

**Comment by derrgoo** [comment]
From Jurial...

Watched flag is shown if ListItem.PlayCount > 0 and ListItem.DBType (mediatype) is set to movie, episode, video, or set
(or tvshow/season will also show watched if unwatchedepisodes is 0).

Progress shows if Kodi has a resume point and IsResumable is set. A plugin cannot set this directly (just setting a resume point is not enough). It requires the plugin to use the setresolvedurl method of playback, which allows Kodi to manage resume points -- there is also a JSON RPC hack to overwrite the resume point for an item file path, but it is not recommended as it can be buggy.

Alternatively, the plugin can set ListItem.Property(WatchedProgress) with a value from 1-99. This will only work in AH2 and Fuse as this is not a standard infolabel and so requires skin support.

**Comment by epidoma** [comment]
@derrgoo 
Thanks for getting the info from jurial. I remember from past that he wold just say its an addon problem.
This kinda broke Arctic horizon 2 skin for many people. 
And this brings hope for a fix .
@kodifitzwell 
If you manage to fix this , can you please do it for onemar as well ?
this would help so many people with jurial skins, very exiting :)

**Comment by derrgoo** [comment]
Unfortunately, I have been with kodi many years but never learned to code just build builds for community. What he is explaining is quite complicated so the easiest way is use his TMD helper to pull widgets and play from TMDB. Jurial and Tiki are the top skinners and add on devs today.

**Comment by kodifitzwell** [comment]
@epidoma this is currently broken in OneMoar?  can you test movies/tvshows/episodes?

**Comment by kodifitzwell** [comment]
does this currently work on any addon that is not helper?

this is what I get with POV/Nexus/Fuse.

![madweb](https://github.com/kodifitzwell/repo/assets/105136042/101ae7c3-2371-42f5-b05b-16be49189954)

I am definitely setting "WatchedProgress" as after I set it I use `ListItem.getProperty('WatchedProgress')` to check and log the value.

@epidoma interesting that it seems to partially work.  there are at least 3 icons overlaid to create it.  the green part (percentage or "WatchedProgress"), the background dark circle, and the clock.  seems to only be rendering the green part.

**Comment by derrgoo** [comment]
> @epidoma this is currently broken in OneMoar?  can you test movies/tvshows/episodes?

OneMoar does mark progress icon but it does it like H2 with omega. Clock missing. It seems jurial only fixed for tmdb player. Pic below. All other addons nothing comes up. Also seems like scribble for track not working. This allows you to resume on any box in house. 

![image](https://github.com/kodifitzwell/repo/assets/63697905/167f7734-fa1d-45b0-972c-4dd5c619c978)

**Comment by kodifitzwell** [comment]
>Also seems like Trakt Scrobble for track not working.

you keep saying this but no log.  marking watched / unwatched worked in my test with trakt the first time you made this claim.

Omega + AF seem to be keys.  my POV update (not yet published) works.  I will wait to push it until the trakt business gets sorted.

![omega](https://github.com/kodifitzwell/repo/assets/105136042/5f7ab9c3-8bc4-47da-b3d9-1f94783d62f3)

**Comment by derrgoo** [comment]
Great to hear you got it working. I get my MacBook back today so I can try to get you a log.

**Comment by derrgoo** [comment]
Man!! It looks like I had something corrupt because I wiped everything and tested pov+fen and it is working correctly now! Just the green part in the clock missing which you just fixed.  So as far as Scrobble it is working correctly now with fresh install. 👍
