### ISSUE TITLE
POV Search Paths

### ISSUE THREAD

**Issue by ivarbrandt** [kodifitzwell/repo#16]
Hey dude. Hope all is well.

I've been asked to implement POV search functionality into my skins so I would like to know the specific search paths that POV uses. I know POV is fork of FEN so the paths may be similar but I just wanted to make sure. Here are the paths that I need:

Movies
TV Shows
Collections (Movies)
Actors/Actresses
IMDb or TMDb Keywords (Movies)
IMDb or TMDb Keywords (TV Shows)

If POV doesn't utilize all of those paths please let me know so I can code those exceptions into my skin accordingly.

**Comment by ivarbrandt** [comment]
Awesome thanks. Do you have a search path for TRAKT lists?

**Comment by kodifitzwell** [comment]
plugin://plugin.video.pov/?mode=build_trakt_list.search_trakt_lists&search_title=

**Comment by ivarbrandt** [comment]
Thank you. I implemented the search paths and everything is working smoothly with a few exceptions that I thought I should make you aware of:

1. Keyword search does not work for movies or tv shows. I also tried it directly from the addon but it didn't work either. I think that was the cause of the error on line 1784 in the log I'm adding below.
2. When the widget for collections loads I get a popup that looks like the image below. It still loads the collections results correctly though.

![screenshot00003](https://github.com/kodifitzwell/repo/assets/54084201/031692f1-16aa-4ef2-9a4b-8437ed6fb8d4)

3. When loading the search window one of the empty querys makes the keyboard pop up. Not sure which one.
4. When loading the search window and a query hasn't been entered yet I'm getting an error on line 1741. Please see the attached kodi log.

[kodi.log](https://github.com/kodifitzwell/repo/files/15042267/kodi.log)

**Comment by kodifitzwell** [comment]
1) that code has been untouched as I don't use imdb personally.  I'm not surprised, likely has to do with website changes.  I will have to work on that.
2) collections or actor?  I'm thinking actor likely due to an empty query.
3) is the user supposed to enter query in the skin or my addon?
4) again, is it normal to send empty queries?

**Comment by kodifitzwell** [comment]
I was able to duplicate the empty window by search with a space (' ') for actor, but not if I selected OK ('') or Cancel.

I have fixed it on my end.

I'm not sure you were sending an "empty" search then, and in any case if the user is supposed to enter the query in the skin, if it is "empty" would it be better to avoid the call to the addon?

**Comment by kodifitzwell** [comment]
although the imdb search return no results, I could not duplicate the errors.

are you sure they are not related to `unsupported protocol(pplugin)`:
```
2024-04-19 08:51:09.819 T:18312 warning <general>: XFILE::CDirectoryFactory::Create - unsupported protocol(pplugin) in pplugin://plugin.video.pov/?mode=imdb_build_keyword_results&media_type=movie&query=
2024-04-19 08:56:41.966 T:5152  warning <general>: XFILE::CDirectoryFactory::Create - unsupported protocol(pplugin) in pplugin://plugin.video.pov/?mode=imdb_build_keyword_results&media_type=movie&query=
2024-04-19 08:56:49.904 T:5152  warning <general>: XFILE::CDirectoryFactory::Create - unsupported protocol(pplugin) in pplugin://plugin.video.pov/?mode=imdb_build_keyword_results&media_type=movie&query=harry%20potter
```

**Comment by ivarbrandt** [comment]
>1. that code has been untouched as I don't use imdb personally. I'm not surprised, likely has to do with website changes. I will have to work on that.

All good. I'll test it out later after you have updated the code.

>2. collections or actor? I'm thinking actor likely due to an empty query.

Not sure actually. Could be actor. I only said collections cause when that widget was loading it would show the popup. You may be right though.

>3. is the user supposed to enter query in the skin or my addon?

The user enters the query in my skin and then it get passed as an infolabel into the search path like this:
`plugin://plugin.video.pov/?mode=build_movie_list&action=tmdb_movies_search&query=$INFO[Skin.String(SearchInputEncoded)]`

> are you sure they are not related to unsupported protocol(pplugin):

LOL. Whoops. The extra p would definitely mess things up.

**Comment by kodifitzwell** [comment]
thanks, when I get some time.

I have to ask again your thoughts on sending "empty" searches.  would not be best to avoid the call the addon?

**Comment by ivarbrandt** [comment]
Well idk how to do it otherwise as the widgets need a path from which to pull content from. That path is the search path and yes the query will be empty but only temporarily until the user enters a search term in. 

I'm not sure how to not call the addon when the search window is opened and then call it when a search term is entered.

**Comment by kodifitzwell** [comment]
not at home to test, but looking at your repo online, I see this is the query that gets concatenated: `$INFO[Skin.String(SearchInputEncoded)]`.

maybe add to the conditions something like?

    condition="!String.IsEmpty(Skin.String(SearchInputEncoded)) + String.IsEqual(Skin.String(current_search_provider),3)"

you might or might not need the `$INFO[...]` bit, idk.  if it even works, this probs takes care of a true empty string, but the var suggests maybe it gets encoded so a space would be sent.  on my end I have stripped the received query and will not proceed if it doesn't exist.  not sure how `$INFO[Skin.String(SearchInputEncoded)]` gets collected, but if it is a python file you author, maybe check for "empty" there before setting the `Skin.String` bit too.

**Comment by ivarbrandt** [comment]
Solid suggestions man. I'll give them a shot and let you know how it goes.

**Comment by ivarbrandt** [comment]
Looks like there's no need to check for the true empty string. Whatever you did worked beautifully. Thank you.
