### ISSUE TITLE
Feature request (POV)

### ISSUE THREAD

**Issue by Sovilor** [kodifitzwell/repo#19]
Hello, thanks for your efforts.
If it's possible please add this feature to Results:
Max results per quality
Maximum results

I can't manage to have less than 120 in results list, no matter what.

Thank you.

**Comment by kodifitzwell** [comment]
I would suggest you use the "Results" settings, "Results Sorting" as "Size, Quality, Provider" and set a file size limit.

once you receive the results, from the context menu you can also filter results.

https://github.com/kodifitzwell/repo/assets/105136042/0ed4e4df-2852-410b-86fb-dd90018761ea

**Comment by Sovilor** [comment]
You got 77 results, i use 2 debrid services, i get 140 results for 1 selected quilty with size limit 20.

**Comment by kodifitzwell** [comment]
> If at least we have an option to set max number for results, that would be useful.

I disagree.  if you have a max limit of 40 or no limit and you get 140, you still start at the top of the list, no?
