### ISSUE TITLE
OneMoar returns deprecated

### ISSUE THREAD

**Issue by ohmichael** [kodifitzwell/repo#2]
I know you are the developer KodiFitzWell and I tried tagging you on Reddit but it wouldn’t let me for some reason but anyways shows version 4.06.02 for some reason and it says deprecated next to it and when I try to update it says unable to install or update so I checked the repo on here on github and it shows version 4.06.02 on the addons.xml but on the files itself it still shows 4.06.01 weird hopefully you catch it or maybe you are behind on updating the files 🤷‍♂️ whichever the case I hope you either read this or someone alerts you by other ways because idk how else possible. Wonderful addon though.
Oh yeah your repo you commented someone with “the link” on Reddit I tried adding it to my files manager on kodi omega exactly as they typed it but the link kept returning with incorrect or something - so I’m just going to my computer manually to download, then send it to my nvidia shield tv to install 😮‍💨
I’m using the newest kodi arm8 version of Omega as well….
Hope that information above helps.

**Comment by kodifitzwell** [comment]
thanks for the kind words!

OneMoar is deprecated in favor of Infinity.
![repo](https://github.com/kodifitzwell/repo/assets/105136042/5b92b82a-7945-4b34-a739-359e13cc836b)

the official repo is still `kodifitzwell.github.io/repo` where you can install the `repository.kodifitzwell-0.0.1.zip`.  the benefit of the addons here is that it uses the kodi update process, so users will be notified.  to install addons from here, use "Install from repository..."

I believe that reddit thread you're referring to is about `kodifitzwell.github.io/repo/packages`.  going forward that location will likely hold "deprecated" addons like afFENity and maybe OneMoar.  these addons may never be updated again (never say never).  to install addons from here, use "Install from zip file..."

so you're correct, I'm making some updates to the repo incrementally that required some behind the scenes stuff.  should all be sorted with the final update this weekend.  if all else fails:

1. from kodi, disable and uninstall the repo
2. check `special://home/addons/packages` and delete `repository.kodifitzwell-0.0.1.zip`
3. repeat the repo install process
4. "Install from repository..."

**Comment by ohmichael** [comment]
Thanks I’ll close this now
