### ISSUE TITLE
POV - Next Episodes doesn't show Rewatches

### ISSUE THREAD

**Issue by youknowmypeach** [kodifitzwell/repo#2]
Hello!
First of all, big thanks to kodifitzwell for the amazing work on the POV add-on; I've been using it for a few months and it's fantastic!

I have a question regarding the Next Episodes section: the POV add-on doesn't show up episodes for series already marked as watched on Trakt, even if they're marked as "Rewatching". However, the Affenity add-on does show all episodes, whether I'm watching for the first time or rewatching.

I have "Hide watched episodes" toggled off and checked every single setting to compare both add-ons but idk if I'm missing something in the settings that's keeping me from seeing all eps or if it's the POV add-on itself that's configured to not show rewatches.

In no way does this stop me from using POV as I absolutely love the interface and how fast it is. If it's not an issue that's being blocked by some kind of setting I haven't found, I do believe it would be an amazing improvement to the add-on.

Thank you!

**Comment by kodifitzwell** [comment]
thanks for using the addon.

there is no setting that affects this.  I'll have to take another look at the trakt api and the addons code and see what the differences are.  this will take a bit of time, I am not a trakt user myself so I have to do some setup.  might be a few updates out.

**Comment by youknowmypeach** [comment]
thanks for the quick reply! not a problem, looking forward to the next updates!
