### ISSUE TITLE
POV 3.x.x

### ISSUE THREAD

**Issue by Tikipeter** [kodifitzwell/repo#2]
Hi there mate.

Great job on `3.x.x` of POV. Looking good moving forward. Good to see you've got at least some time and plenty of ideas to work through. Really like what you're doing. :)

I quite like the idea of your `Features` tab in Settings. I was hoping you would let me steal that idea and implement similar in Fen. It will be good for some settings that don't quite fit in other places and are generally unique features of the addon.

**Comment by kodifitzwell** [comment]
absolutely feel free.  its really your baby.  believe it or not I never really used "Extras" or "Next Episodes" until I started tinkering with the Fen code.  so I thought a "Features" category would be good to highlight such things.

thanks again!

**Comment by Tikipeter** [comment]
Thanks mate. Appreciate it. :)

Extras is my favorite thing, but not for everyone. I'm more a fiddle around looking at things rather than an actually watch things type of person. Not good really.
