### ISSUE TITLE
No poster image in Next Episode using Flix view

### ISSUE THREAD

**Issue by edjalmobf** [kodifitzwell/repo#2]
Hi! 
I just read about your addon yesterday and due to automatically subtitles I install it, thanks :)
I use it with Nimbus skin, and set the next episode as widget using the poster as display type. The widget loads the content but without image. I checked too inside the add-on. If you select the view as Flix you got no poster. Would be great if you can fix that.
Thanks in advance!

**Comment by kodifitzwell** [comment]
[these are the art label/values currently set for each item in next episodes](https://romanvm.github.io/Kodistubs/_autosummary/xbmcgui.html#xbmcgui.ListItem.setArt).

    'poster'
    'fanart'
    'thumb'
    'icon'
    'banner'
    'clearart'
    'clearlogo'
    'landscape'
    'tvshow.poster'
    'tvshow.clearart'
    'tvshow.clearlogo'
    'tvshow.landscape'
    'tvshow.banner'

so I definitely "got a poster" as I see it clearly in the default skin.

confirm with the skin dev which label/value they are seeking.  additionally the view type, content type is `view.episodes`, `episodes` respectively, idk if it matters.

**Comment by edjalmobf** [comment]
Got it! So it's something skin related...
This is the skin: https://github.com/ivarbrandt/skin.nimbus
It work well in fen light, but maybe the dev looked only for fen light in the development haha.
