### ISSUE TITLE
POV - Hide Jump to in trakt lists!

### ISSUE THREAD

**Issue by diimaan** [kodifitzwell/repo#3]
Hello! 
First I appreciate your time and thank you for the effort in developing these kodi addons!

I have a question if not a suggestion about hiding the Jump to which appears on top when navigating trakt lists. This is not a major thing if I use the default skin. But when I use something like Fuse or Fentastic or other fancy skins the Jump To appears as first in the widgets. 

Are there any options to hide this? Thank you :)

Diimaan

**Comment by kodifitzwell** [comment]
I don't use a skin or trakt so I've never tested this, but it looks like it's already coded for jump lists not to appear in widgets.

is there specific trakt lists it shows or all of them?  what skin?

**Comment by diimaan** [comment]
My bad! I mistakenly mentioned it is on the widgets page.
But it is on the favorites. I keep minimum widgets and keep everything else on my favorites. The skin is AH2

Here are the screenshots!

![Screenshot 2024-06-25 at 19 31 21](https://github.com/kodifitzwell/repo/assets/3683925/1f74a563-fa65-4e67-8f74-49ef18f08b22)
![Screenshot 2024-06-25 at 19 31 28](https://github.com/kodifitzwell/repo/assets/3683925/da607539-2718-4b26-8e10-7153b3fe1399)

**Comment by kodifitzwell** [comment]
added an option do disable "Jump To..." in the next version.

**Comment by kodifitzwell** [comment]
if you are indeed still on `4.04.09` you missed some important updates in the past two months.

to even be notified of the update when I push it, you are going to have to re-install the repo:

1. from kodi, disable and uninstall the repo
2. check `special://home/addons/packages` and delete `repository.kodifitzwell-0.0.1.zip`
3. repeat the repo install process
4. "Install from repository..."

**Comment by diimaan** [comment]
Oh yes! I am indeed still on 4.04.09! I will follow the steps and do the installation to get up to date!

**Comment by diimaan** [comment]
I am now on 4.07.01! Hope this is the latest one :)
