### ISSUE TITLE
BUG: Movie and TV Show box/poster art is missing in Dradis and Infinity

### ISSUE THREAD

**Issue by Hemicrusher** [kodifitzwell/repo#3]
Movie and TV Show box/poster art is missing in both Dradis and Infinity. 

[Infinity screen showing the missing art](https://i.imgur.com/qwDx9wS.jpg)

I cleared thumbnails, cache etc, but they are still missing. POV is not having the issue.

[My log file.](https://paste.kodi.tv/unoqizesob)

**Comment by Hemicrusher** [comment]
I just went back and checked in Dradis and Infinity and some of the art is now showing, but it's random. In Infinity, going into My Movies > Trakt Watchlist....they are all missing. Going into Discover Movies >Trending (Trakt)... 20% are missing. No issues with POV or that other addon we all know.

**Comment by kodifitzwell** [comment]
interesting.  I do not believe this is due to my addons.  look at the sql errors I collected from [your log file](https://paste.kodi.tv/sidifibibe.kodi) that relate to `Textures13.db`.  I would clear all the caches, delete `Textures13.db` and restart kodi.

    Profile directory/Database/Textures13.db

I can't duplicate on the default skin.

**Comment by Hemicrusher** [comment]
So, I went back into Kodi to delete the Texture13.db, and Kodi will not start now. Just freezes on the Kodi Omega logo. This is the second time this has happened, and I have no idea why. I really don't run much, and the last time it happened, I was using a different skin.

What pisses me off, is Kodi does not have a safe mode, or some type of recovery if there is a failure to start. And with Google TV locking down everything so I can't even use a file manager to access the Kodi directory. I even deleted Kodi cache in GoogleTV, force stopped Kodi etc, but it still freezes.

Unless you have any suggestions, you can close this since it looks like I have to wipe Kodi and reinstall.

Thanks!
