### ISSUE TITLE
POV feature request.

### ISSUE THREAD

**Issue by Hemicrusher** [kodifitzwell/repo#3]
Not sure if this is a feature request, or an issue I am having. Currently using POV in Kodi 21 on an ONN 4K Google TV device. 

When I play a trailer, there are no controls to pause, rewind or forward a video. Sometimes I'll want to show my wife a trailer I started, to see if she is interested, and the trailer will resume where I exited it. I am then unable to rewind it, so she can see it from the start. The only way I can reset it is exiting Kodi, watching the video until the end, or clearing POVs cache. 

Is there a way to add controls, or use YouTube the way it is in Dradis? Or at least have it clear the progress when exiting the video? 

Thanks!

**Comment by kodifitzwell** [comment]
>Is there a way to add controls, or use YouTube the way it is in Dradis? Or at least have it clear the progress when exiting the video?

Yes.  took a quick look and not sure which to do yet.  unfortunately, won't be able to get to this as quick as usual but top of the list.

**Comment by Hemicrusher** [comment]
> > Is there a way to add controls, or use YouTube the way it is in Dradis? Or at least have it clear the progress when exiting the video?
> 
> Yes. took a quick look and not sure which to do yet. unfortunately, won't be able to get to this as quick as usual but top of the list.

Awesome!

Thanks!

**Comment by kodifitzwell** [comment]
I had a chance to look into this this morning.

>use YouTube the way it is in Dradis?

if I send it out to the youtube addon, you get controls but it returns to the movie/tvshow list rather than the Extras page.

> Or at least have it clear the progress when exiting the video?

the progress is controlled by the youtube addon setting:

    settings > advanced > use local playback history

I'm inclined to leave it as it is for now and suggest turning off the history unless you think otherwise?

**Comment by Hemicrusher** [comment]
> ```
> settings > advanced > use local playback history
> ```
> 
> I'm inclined to leave it as it is for now and suggest turning off the history unless you think otherwise?

That will work for me...

Thanks!
