### ISSUE TITLE
Feature Request - Sorting in POV

### ISSUE THREAD

**Issue by Hemicrusher** [kodifitzwell/repo#4]
Is there anyway to be able to sort the Trakt lists under "My Lists"? I use Trakt exclusively to manage my movies and TV, and really only use two items, "TRAKT: Collection" and "TRAKT: Watchlist". I'd like to have those two items above "TRAKT: Trending User Lists".....basically the way Fen Light has them sorted. 

Thanks again for all the work you put in these addons!

**Comment by kodifitzwell** [comment]
like this?

![trakt](https://github.com/kodifitzwell/repo/assets/105136042/a50827d4-4d08-4014-9e9e-563ddd4cc30c)

**Comment by kodifitzwell** [comment]
also you can create a shortcut folder from the settings menu and create a menu with the items you prefer, then add that to a menu.

![shortcut](https://github.com/kodifitzwell/repo/assets/105136042/b14cf99b-90a9-4b44-98b6-59c3833c33b8)

**Comment by Hemicrusher** [comment]
Yes, like the menu above.

Oh, didn't know about the folder creation....I'll check that out when I get home later.

Thanks!

**Comment by Hemicrusher** [comment]
> also you can create a shortcut folder from the settings menu and create a menu with the items you prefer, then add that to a menu.
> 

Okay, that works perfectly!

Closing this....
