### ISSUE TITLE
Play Random doesn't work

### ISSUE THREAD

**Issue by Jexetic** [kodifitzwell/repo#4]
Plugin: POV

The "Play Random" option for tv shows doesn't seem to work, it just throws up an error every time.

Logs: https://paste.kodi.tv/pulihicipu

Tried on both Mac and Windows.

**Comment by kodifitzwell** [comment]
thanks for using the addon and the log was helpful.

should be fixed in `4.08.04`, lmk if it is not or please close the issue.

https://github.com/user-attachments/assets/fafcedc5-ffff-44a9-a784-923b67fc4677

**Comment by Jexetic** [comment]
Awesome, thanks for the quick fix!
