### ISSUE TITLE
POV: Continual Random Play only plays one episode

### ISSUE THREAD

**Issue by Jexetic** [kodifitzwell/repo#5]
Ran into one more issue with the random play option. Continual random play will only play one episode. When the episode nears the end, it'll show the popup for the next chronological episode, and if that popup isn't acted on it plays nothing (even though normally it would move to the next episode on it's own for chronological playing). The expected behavior I assume would be to play another random episode without needing to interact. I can provide a log tomorrow if needed.

**Comment by kodifitzwell** [comment]
I can reproduce this and a quick look has me scratching my head.  below is my log.  at line 2 you can see the first link open, I FF a bunch, then line 61 shows the second link open and it just stops.  the `error` after that just gives a reason `Error creating demuxer`.

    01: 2024-08-05 10:59:35.798 T:7984     info <general>: Loading skin file: D:\nexus\portable_data\addons\plugin.video.pov\resources\skins\Default\1080i\yes_no_progress_media.xml, load type: LOAD_ON_GUI_INIT
    02: 2024-08-05 10:59:45.742 T:7984     info <general>: VideoPlayer::OpenFile: https://lax5.download.real-debrid.com/d/4QFRXSVAOGPFW23/Batman.Caped.Crusader.s01e05.mkv
    03: 2024-08-05 10:59:46.210 T:7424     info <general>: Creating InputStream
    04: 2024-08-05 10:59:47.091 T:7424     info <general>: Creating Demuxer
    05: 2024-08-05 10:59:48.899 T:7424     info <general>: Opening stream: 0 source: 256
    06: 2024-08-05 10:59:48.899 T:7424     info <general>: Creating video codec with codec id: 27
    07: 2024-08-05 10:59:48.899 T:7424     info <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
    08: 2024-08-05 10:59:48.899 T:7424     info <general>: Creating video thread
    09: 2024-08-05 10:59:48.900 T:9704     info <general>: running thread: video_thread
    10: 2024-08-05 10:59:48.901 T:7424     info <general>: Opening stream: 2 source: 256
    11: 2024-08-05 10:59:48.901 T:7424     info <general>: Finding audio codec for: 86056
    12: 2024-08-05 10:59:48.901 T:7424     info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder eac3
    13: 2024-08-05 10:59:48.901 T:7424     info <general>: CVideoPlayerAudio::OpenStream: Allowing max Out-Of-Sync Value of 10 ms
    14: 2024-08-05 10:59:48.901 T:7424     info <general>: Creating audio thread
    15: 2024-08-05 10:59:48.902 T:8464     info <general>: running thread: CVideoPlayerAudio::Process()
    16: 2024-08-05 10:59:48.902 T:7424     info <general>: Opening stream: 5 source: 256
    17: 2024-08-05 10:59:48.902 T:7424     info <general>: CDVDSubtitlesLibass: Using libass version 1502000
    18: 2024-08-05 10:59:48.902 T:7424     info <general>: CDVDSubtitlesLibass: Creating ASS library structure
    19: 2024-08-05 10:59:48.902 T:7424     info <general>: CDVDSubtitlesLibass: Initializing ASS Renderer
    20: 2024-08-05 10:59:48.904 T:7424     info <general>: CDVDSubtitlesLibass: Initializing ASS library font settings
    21: 2024-08-05 10:59:48.911 T:7424     info <general>: CDVDSubtitlesLibass: Creating new ASS track
    22: 2024-08-05 10:59:48.911 T:9704     info <general>: DXVA::CContext::CreateContext: creating discrete d3d11va device for decoding.
    23: 2024-08-05 10:59:48.913 T:8464     info <general>: Creating audio stream (codec id: 86056, channels: 6, sample rate: 48000, no pass-through)
    24: 2024-08-05 10:59:48.913 T:4424     info <general>: CActiveAESink::OpenSink - initialize sink
    25: 2024-08-05 10:59:48.985 T:9704     info <general>: DXVA::CDecoder::Open: Total video memory available is 12109 MB (dedicated = 3962 MB, shared = 8147 MB)
    26: 2024-08-05 10:59:49.018 T:7984     info <general>: DXVA::CProcessorHD::InitProcessor: supported deinterlace methods: blend:yes, bob:yes, adaptive:yes, mocomp:no.
    27: 2024-08-05 10:59:49.019 T:7984  warning <general>: CRendererHQ::CheckVideoParameters: chosen scaling method 1 is not supported by renderer
    28: 2024-08-05 10:59:49.049 T:7984     info <general>: Loading skin file: VideoFullScreen.xml, load type: KEEP_IN_MEMORY
    29: 2024-08-05 10:59:49.370 T:9704     info <general>: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 41727
    30: 2024-08-05 10:59:51.631 T:7984     info <general>: Loading skin file: DialogFullScreenInfo.xml, load type: KEEP_IN_MEMORY
    31: 2024-08-05 11:00:00.686 T:9704  warning <general>: CVideoPlayerVideo::OutputPicture - timeout waiting for buffer
    32: 2024-08-05 11:00:02.604 T:9704     info <general>: DXVA::CDecoder::Open: Total video memory available is 12109 MB (dedicated = 3962 MB, shared = 8147 MB)
    33: 2024-08-05 11:00:02.698 T:7984     info <general>: DXVA::CDecoder::Close: closing decoder.
    34: 2024-08-05 11:00:11.384 T:9704  warning <general>: CVideoPlayerVideo::OutputPicture - timeout waiting for buffer
    35: 2024-08-05 11:00:11.957 T:9704     info <general>: DXVA::CDecoder::Open: Total video memory available is 12109 MB (dedicated = 3962 MB, shared = 8147 MB)
    36: 2024-08-05 11:00:12.081 T:7984     info <general>: DXVA::CDecoder::Close: closing decoder.
    37: 2024-08-05 11:00:18.863 T:9704     info <general>: DXVA::CDecoder::Open: Total video memory available is 12109 MB (dedicated = 3962 MB, shared = 8147 MB)
    38: 2024-08-05 11:00:18.902 T:8464     info <general>: CVideoPlayerAudio::ProcessDecoderOutput: Changed max allowed Out-Of-Sync value to 16 ms due self-learning
    39: 2024-08-05 11:00:18.981 T:7984     info <general>: DXVA::CDecoder::Close: closing decoder.
    40: 2024-08-05 11:00:21.915 T:9704  warning <general>: CVideoPlayerVideo::OutputPicture - timeout waiting for buffer
    41: 2024-08-05 11:00:22.557 T:9704     info <general>: DXVA::CDecoder::Open: Total video memory available is 12109 MB (dedicated = 3962 MB, shared = 8147 MB)
    42: 2024-08-05 11:00:22.665 T:7984     info <general>: DXVA::CDecoder::Close: closing decoder.
    43: 2024-08-05 11:02:08.632 T:7424     info <general>: CVideoPlayer::Process - eof reading from demuxer
    44: 2024-08-05 11:02:08.633 T:7424     info <general>: CVideoPlayer::OnExit()
    45: 2024-08-05 11:02:08.633 T:7424     info <general>: VideoPlayer: eof, waiting for queues to empty
    46: 2024-08-05 11:02:08.633 T:7424     info <general>: Closing stream player 1
    47: 2024-08-05 11:02:08.633 T:7424     info <general>: CDVDMessageQueue(audio)::WaitUntilEmpty
    48: 2024-08-05 11:02:08.633 T:7424     info <general>: Waiting for audio thread to exit
    49: 2024-08-05 11:02:08.633 T:8464     info <general>: thread end: CVideoPlayerAudio::OnExit()
    50: 2024-08-05 11:02:08.633 T:7424     info <general>: Closing audio device
    51: 2024-08-05 11:02:08.697 T:7424     info <general>: Deleting audio codec
    52: 2024-08-05 11:02:08.697 T:7424     info <general>: Closing stream player 2
    53: 2024-08-05 11:02:08.697 T:7424     info <general>: CDVDMessageQueue(video)::WaitUntilEmpty
    54: 2024-08-05 11:02:08.720 T:7424     info <general>: waiting for video thread to exit
    55: 2024-08-05 11:02:08.720 T:9704     info <general>: thread end: video_thread
    56: 2024-08-05 11:02:08.720 T:7424     info <general>: deleting video codec
    57: 2024-08-05 11:02:08.720 T:7424     info <general>: Closing stream player 3
    58: 2024-08-05 11:02:08.951 T:10236   error <general>: EXCEPTION: Kodi is not playing any media file
    59: 2024-08-05 11:02:08.953 T:10236    info <general>: CPythonInvoker(2, D:\nexus\portable_data\addons\plugin.video.pov\resources\lib\pov.py): waiting on thread 9068
    60: 2024-08-05 11:02:09.074 T:4424     info <general>: CActiveAESink::OpenSink - initialize sink
    61: 2024-08-05 11:02:09.412 T:7984     info <general>: VideoPlayer::OpenFile: https://lax5.download.real-debrid.com/d/WEMZ7HKJZ6LYS10/Batman.Caped.Crusader.s01e07.mkv
    62: 2024-08-05 11:02:09.891 T:9912     info <general>: Creating InputStream
    63: 2024-08-05 11:02:10.249 T:7984     info <general>: CVideoPlayer::CloseFile()
    64: 2024-08-05 11:02:10.249 T:7984     info <general>: DXVA::CDecoder::Close: closing decoder.
    65: 2024-08-05 11:02:10.249 T:7984     info <general>: DXVA: closing decoder context.
    66: 2024-08-05 11:02:10.268 T:7984     info <general>: VideoPlayer: waiting for threads to exit
    67: 2024-08-05 11:02:10.881 T:9912     info <general>: Creating Demuxer
    68: 2024-08-05 11:02:10.881 T:9912    error <general>: CVideoPlayer::OpenDemuxStream - Error creating demuxer
    69: 2024-08-05 11:02:10.882 T:9912     info <general>: CVideoPlayer::OnExit()
    70: 2024-08-05 11:02:10.938 T:7984     info <general>: VideoPlayer: finished waiting
    71: 2024-08-05 11:02:10.938 T:7984     info <general>: CVideoPlayer::CloseFile()
    72: 2024-08-05 11:02:10.938 T:7984     info <general>: VideoPlayer: waiting for threads to exit
    73: 2024-08-05 11:02:10.938 T:7984     info <general>: VideoPlayer: finished waiting
    74: 2024-08-05 11:02:10.942 T:7984    error <general>: Control 50 in window 10025 has been asked to focus, but it can't
    75: 2024-08-05 11:03:13.282 T:11144   error <general>: Unable to find plugin 
    76: 2024-08-05 11:03:13.282 T:11144   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://
    77: 2024-08-05 11:03:13.282 T:7984    error <general>: CGUIMediaWindow::GetDirectory(plugin://) failed
