### ISSUE TITLE
POV - Error when using "Marked Watched Trakt"

### ISSUE THREAD

**Issue by Hemicrusher** [kodifitzwell/repo#6]
When attempting to mark a series episode as watched using the context menu item, "Marked Watched Trakt", POV produces an error. 

[Link to log file.](https://paste.kodi.tv/efegalatuk)

I cleared cache in POV, unauthorized, and reauthorized Trakt, and also tried to uninstall POV, then authorizing Trakt, yet the error still happens.

Thanks!

**Comment by kodifitzwell** [comment]
I see what the issue is.  thanks for reporting it, will be in the next update.

**Comment by Hemicrusher** [comment]
Fixed!

Have a great week!
