### ISSUE TITLE
In Progress TV Shows and Next Episodes showing episodes from hidden TV Shows

### ISSUE THREAD

**Issue by daherlihy** [kodifitzwell/repo#7]
I've only noticed today that episodes from TV Shows that are hidden in Trakt are still appearing in **In Progress TV Shows** and **Next Episodes**. Shouldn't these episodes also be hidden?

**Comment by kodifitzwell** [comment]
>episodes from TV Shows that are hidden in Trakt

I'm not a trakt user myself, but looking at the code, hidden shows should be excluded from Next Episodes.
how are you hiding episodes?  according the trakt api, only shows or seasons are hideable.
[https://trakt.docs.apiary.io/#reference/users/add-hidden-items](https://trakt.docs.apiary.io/#reference/users/add-hidden-items)

https://github.com/kodifitzwell/repo/assets/105136042/24519848-e9ee-4559-9500-2980f8c57c93

**Comment by daherlihy** [comment]
> > episodes from TV Shows that are hidden in Trakt
> 
> I'm not a trakt user myself, but looking at the code, hidden shows should be excluded from Next Episodes. how are you hiding episodes? according the trakt api, only shows or seasons are hideable. https://trakt.docs.apiary.io/#reference/users/add-hidden-items
> 
>  kodi_pp8qD8xNBI.mp4

Yep only the shows can be hidden in Trakt. But the episodes of hidden shows are still showing in the 2 menus I mentioned above - my understanding is that they shouldn't be showing (?)

**Comment by daherlihy** [comment]
The video you showed doesn't involve hiding a show on Trakt which is the key part.

Basically on Trakt, you can hide or add a TV show/series to Hidden, for instance if you got fed up of it after a while. When you hide them, they'll appear then in the Hidden section on the Trakt account: https://trakt.tv/settings/hidden (they can be removed if you want later). In theory, these hidden shows should then not appear for users in their app or addon sections such as In Progress TV Shows or Next Episodes. There are many addons which have/had this setup, so I'm hoping you can incorporate it.

**Comment by kodifitzwell** [comment]
right, so when I hide a show from Next Episodes *in the addon* it shows up here, likely same as if I hide the show on the trakt website.
![capture](https://github.com/kodifitzwell/repo/assets/105136042/0de7108f-e206-4f96-983c-b70ab1e6530d)

if it does not work that way for you, share some examples of your shows so I can test.

**Comment by kodifitzwell** [comment]
you can share the video if you want.  I'm certain I understand your question though.  when you hide an item via trakt website, is still shows in Next Episodes.

when Next Episodes creates the list, it pulls data from trakt.  it works correct in my test (a new one using the website).

https://github.com/kodifitzwell/repo/assets/105136042/1402b601-13e0-4f2d-ad27-91c5d9d2766b

so again, if it does not work for you, share some show examples so I can test.

my opinion right now is that I don't want to support this for the In Progress section.

**Comment by daherlihy** [comment]
Ok turns out I was having an issue with the cache on my device, was unable to recreate on a different device. Everything resolved so, take sorry for taking up your time. 

However I inadvertently came across an issue accessing the lists inside Trakt My Lists, see the log here: https://paste.kodi.tv/womiyutipe

Let me know if you'd like me to open a separate issue for this.

**Comment by kodifitzwell** [comment]
thanks for the log,  I think I see the issue.

all these list are private or your profile is private?
do you have any public lists that are inaccessible?

**Comment by daherlihy** [comment]
Yep it's private and indeed I can't access a liked list on another private account. No issue accessing a like list on a public account. 

Any chance we could view lists on private accounts? 😉

**Comment by kodifitzwell** [comment]
[https://trakt.docs.apiary.io/#reference/users/list-items](https://trakt.docs.apiary.io/#reference/users/list-items)

the api states "OAuth Optional" so I would take that to mean that it should not be needed to view the list.  I did make a change from the original Fen code in one of the more recent updates.  when I have a bit of time I'll revert back.

**Comment by kodifitzwell** [comment]
>Only asking because I raised a feature request for a different addon and referred to your addon as a working example, only then to get to be ignorantly told "USE POW THEN" and the issue closed, and deleted.

I wonder what addon that was. 🤔

**Comment by daherlihy** [comment]
Excellent thanks for all this. I did for sure access lists previously on your add-on so glad I'm spotted it today. 

> > Only asking because I raised a feature request for a different addon and referred to your addon as a working example, only then to get to be ignorantly told "USE POW THEN" and the issue closed, and deleted.
> 
> I wonder what addon that was. 🤔

I'm not gonna say but what I will say is that no matter what I said to the dev, it just sent over his head 🔍😉 (and yes I also meant POV, not POW 💥🤣)

**Comment by kodifitzwell** [comment]
did `4.04.09` resolve the issues?  if so please close the issue (or let me know so I can) or follow up with another log file if you can.

**Comment by daherlihy** [comment]
Yes everything resolved in 4.04.09, huge thanks to you for this! I'll also close https://github.com/Tikipeter/tikipeter.github.io/issues/24 👍

**Comment by kodifitzwell** [comment]
> I'm not gonna say but...

in my mind I already knew.
