### ISSUE TITLE
results display "details" variant

### ISSUE THREAD

**Issue by Kaan88** [kodifitzwell/repo#8]
“The ‘List details’ feature appears to be not working correctly. Fen used to display file information on the right side instead of movie details. Also text doesn't scroll so I can't see the complete file name, not even when I use extra info context menu.

The only noticeable change from the default list view is the reduced font size as far as I can tell.

**Comment by kodifitzwell** [comment]
> Also text doesn't scroll so I can't see the complete file name, not even when I use extra info context menu.

correct, at an earlier time I added the scroll attribute but the way the xml is currently constructed its one long label so the the colored "TITLE:" text also scrolled which I didn't like.  on the list for the future.


> The ‘List details’ feature appears to be not working correctly.

this is the "list details" from Fen, same as it is now.
![source_results_list details](https://github.com/kodifitzwell/repo/assets/105136042/2f02ce30-d267-4dfd-89e3-3eee3ccc09e0)

> The only noticeable change from the default list view is the reduced font size as far as I can tell.

the info is presently in slightly different order too, but you're right they are very similar.  I almost removed the list details along with the other views.

> Fen used to display file information on the right side instead of movie details.

this is the "info list details" from Fen, which I removed.  the info pane is redundant as the only bit of info not already present is the hash, which is available from the info/context menu extra info.
![source_results_infolist details](https://github.com/kodifitzwell/repo/assets/105136042/21aec8d6-1e54-4c3a-9d44-4d5bcb10a934)

the number of times I've had to use these elements outside of testing is zero.  to my knowledge, you can't copy/paste the text.  I'm not against making changes, but I am curious how you use each of the elements consistently?

**Comment by Kaan88** [comment]
Sorry about the wrong name for the list.

I liked it because I could quickly check out the release groups from the right panel, instead of waiting for the scroll to text. This was the only reason I used it.

**Comment by kodifitzwell** [comment]
I added back the info list style, but scroll will be for a future date.  if this has been satisfied in the update to `4.04.01~rc5` please return and close this issue.

**Comment by Kaan88** [comment]
Beautiful, thanks!
