### ISSUE TITLE
Playing TV Shows

### ISSUE THREAD

**Issue by TheOGuser** [kodifitzwell/repo#8]
Hello Team.
I have an issue with trying to play TV Shows with play Next.

Using Kodi 21
Kodi Settings
Media
Videos
Default Select Action
Show Information.

In Onemoar Settings
Playback
Enable PlayNext Popup--------- Enable

Click OK

Go into TV Shows and click any episode and nothing seems to happen.

I have RD enabled and CoCo Scrapers enabled.

Movies are working fine.

**Comment by kodifitzwell** [comment]
this works in part in kodi 20. something changed in kodi 21 as it seems to try and play `plugin://.../VIDEO_TS/VIDEO_TS.IFO`.  what do the kodi devs have to say about this?

I would suggest restoring the default action to Play.

**Comment by TheOGuser** [comment]
> this works in part in kodi 20. something changed in kodi 21 as it seems to try and play `plugin://.../VIDEO_TS/VIDEO_TS.IFO`. what do the kodi devs have to say about this?
> 
> I would suggest restoring the default action to Play.

Ta for the suggestion. I now only use FEN and OneMoar, so kodi forum is not an option to show logs or speak to for support. 

So was hoping you could help.

Show information just gives a better experience, as using horizon 2. 

If you cannot fix it, then close the issue. Ta for your effort.

**Comment by kodifitzwell** [comment]
>If you cannot fix it, then close the issue.

what is for me to fix?  it works in part in 20 and not in 21.  the string `VIDEO_TS/VIDEO_TS.IFO` is nowhere in the addons code, so how kodi concatenates `plugin://plugin.video.onemoar/VIDEO_TS/VIDEO_TS.IFO` that fails in 21 is something in the kodi code that needs to be addressed.  I'm not a kodi dev.

**Comment by TheOGuser** [comment]
> > If you cannot fix it, then close the issue.
> 
> what is for me to fix? it works in part in 20 and not in 21. the string `VIDEO_TS/VIDEO_TS.IFO` is nowhere in the addons code, so how kodi concatenates `plugin://plugin.video.onemoar/VIDEO_TS/VIDEO_TS.IFO` that fails in 21 is something in the kodi code that needs to be addressed. I'm not a kodi dev.

I thought it was fixable, as this does not happen in FEN.

**Comment by TheOGuser** [comment]
> > this does not happen in FEN
> 
> and this does not happen in kodi 20.

Fen it is for TV shows then, thxs
